version: "3.1"
# https://docs.docker.com/compose/compose-file/
networks:
  backend:
    driver: bridge

services:

### php ##############################################
  gandagang-lumen:
    image: gandagang-lumen
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php  
    hostname: ${ENV_NAME:-gandagang-lumen}
    environment:
      - ENV_NAME=${ENV_NAME:-gandagang-lumen}
    tty: true
    ports:
    - ${HTTP_PORT:-80}:80
    volumes:
      - ./src:/var/www/gandagang.com/
    networks:
      - backend

### MysqlDB ##############################################
  mysql:
    image: mysql:8.0.18
    container_name: mysql
    restart: unless-stopped
    tty: true
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      # So you don't have to use root, but you can if you like
      - MYSQL_USER=${MYSQL_USER}
      # You can use whatever password you like
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      # Password for root access
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - backend
